[package]
authors = ["Eden <rust@eden2.com>"]
categories = ["database"]
description = "Easy data persistence layer, backed by SQLite"
edition = "2018"
keywords = ["sqlite", "sql"]
license = "MIT OR Apache-2.0"
name = "turbosql"
publish = false
readme = "README.md"
repository = "https://github.com/trevyn/turbosql"
version = "0.0.0"

[dependencies]
anyhow = "1.0.34"
itertools = "0.9.0"
log = "0.4.11"
once_cell = "1.5.2"
rusqlite = {version = "0.24.1", features = ["bundled", "blob"]}
serde = {version = "1.0.117", features = ["derive"]}
toml = "0.5.7"
turbosql_macros = {path = "../turbosql_macros"}

[features]
test = ["turbosql_macros/test"]

[[test]]
name = "integration_test"
path = "tests/integration_test.rs"
required-features = ["test"]
