name: scrapertest

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on:
#       - ubuntu-latest
      - macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
      
    - run: npm run build
      working-directory: 'turbo_frontend'

    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.2'
    
    - run: go get golang.org/dl/go1.15.2
    
    - run: go1.15.2 download

    - name: build rclone lib
      run: ./build-turbo.sh
      working-directory: 'rclone'
   
    - run: cargo build --release --verbose
      working-directory: 'scrapertest'

    - uses: actions/upload-artifact@v2
      with:
        name: scrapertest
        path: target/release/scrapertest

#     - name: Run tests
#       run: cargo test --verbose
