name: scrapertest

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on:
#       - ubuntu-latest
      - macos-10.15

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Go 1.15.2
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.2'

    - name: Build rclone lib
      run: ./build-turbo.sh
      working-directory: 'rclone'
   
    - name: Build Rust binary
      run: cargo build --verbose
      working-directory: 'scrapertest'
      
#     - name: Run tests
#       run: cargo test --verbose
