name: scrapertest

on:
  push:
    branches:
      - master
  #     - dev
  # pull_request:
  #   branches:
  #     - master
  #     - dev

env:
  CARGO_TERM_COLOR: always

jobs:

  test:
    name: Test Rust ${{ matrix.rust }}
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      
      - run: mkdir build
        working-directory: 'turbo_frontend'

      - name: cargo test turbosql_macros
        run: cargo test --features "test" -- --nocapture
        working-directory: 'turbosql_macros'

      - name: cargo test turbosql
        run: cargo test --features "test" -- --nocapture
        working-directory: 'turbosql'

      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'
      
      - run: go get golang.org/dl/go1.15.5
      
      - run: go1.15.5 download

      - name: Build rclone lib
        run: ./build-turbo.sh
        working-directory: 'rclone'

      - name: cargo test scrapertest -- --nocapture
        run: cargo test
        working-directory: 'scrapertest'        

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - run: npm install
        working-directory: 'turbo_frontend'

      - run: npm run build
        working-directory: 'turbo_frontend'

      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'
      
      - run: go get golang.org/dl/go1.15.5
      
      - run: go1.15.5 download

      - name: Build rclone lib
        run: ./build-turbo.sh
        working-directory: 'rclone'
    
      - run: cargo build --release --verbose
        working-directory: 'scrapertest'

      - run: brotli -v scrapertest
        working-directory: 'target/release'

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: target/release/scrapertest.br

        
  release:
    needs: [test, build]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v2

      - id: vars
        run: echo "::set-output name=sha::$(echo $(date '+%y%m%d-%H%M')-${GITHUB_SHA:0:7})"

      - uses: trevyn/generate-release-changelog@master
        id: changelog
        env:
          REPO: ${{ github.repository }}

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.sha }}
          release_name: ${{ steps.vars.outputs.sha }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ubuntu-18.04/scrapertest.br
          asset_name: scrapertest-linux-${{ steps.vars.outputs.sha }}.br
          asset_content_type: application/octet-stream

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos-10.15/scrapertest.br
          asset_name: scrapertest-macos-${{ steps.vars.outputs.sha }}.br
          asset_content_type: application/octet-stream
