name: scrapertest

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on:
#       - ubuntu-latest
      - macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
      
    - name: Set up Go 1.15.2
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.2'
    
    - run: go get golang.org/dl/go1.15.2
    
    - run: go1.15.2 download

    - name: Show working dir
      run: pwd
      working-directory: 'rclone'

    - name: Show ls
      run: ls
      working-directory: 'rclone'

    - name: Build rclone lib
      run: ./build-turbo.sh
      working-directory: 'rclone'
   
    - name: Build Rust binary
      run: cargo build --verbose
      working-directory: 'scrapertest'
      
#     - name: Run tests
#       run: cargo test --verbose
